### ISSUE TITLE
Content formats

### ISSUE THREAD

**Issue by benmerckx** [alineacms/alinea#10]
It would be nice to have a yaml loader which can format rich text as markdown, embedding inner blocks as html:

````yaml
id: ...
title: My entry
body: |
  # Heading
  
  Some text
  <CodeBlock code="..." />
  More text
````
